# Generated by Django 6.1.1 on 2026-09-30 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slug", models.SlugField(unique=True)),
                ("category", models.CharField(max_length=60)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("image_url", models.URLField(blank=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("complete", "Complete"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=240)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=24)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=140)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
